### ISSUE TITLE
Arch Linux-6.2.2内核编译失败

### ISSUE THREAD

**Issue by cmx0223** [WCHSoftGroup/ch343ser_linux#18]
Arch Linux-6.2.2内核编译失败
![image](https://user-images.githubusercontent.com/36349492/224484341-3c2343e4-8875-442f-86d0-6cb237d9b878.png)

**Comment by AbraxasVi** [comment]
![image](https://user-images.githubusercontent.com/17812669/225184049-0332634f-2075-4423-9294-4a5cc5f13b3f.png)
甚至在使用第三方定制内核的Ubuntu里也会报这个错误，不管是liquorix还是xanmod内核
但在最新内核的PVE和树莓派版Ubuntu里又不会报错。

**Comment by Souravgoswami** [comment]
![image](https://user-images.githubusercontent.com/37468605/229469492-dbb87cdc-2bd9-406d-ba2c-b5c683d2f189.png)

![image](https://user-images.githubusercontent.com/37468605/229469613-0b041105-3a51-41b6-b695-59519bb68aa1.png)

Add that to both

```
static void ch343_tty_set_termios(struct tty_struct *tty, const struct ktermios *termios_old)
```

Adding the `const` keyword fixes the compile error.

**Comment by FirstLoveLife** [comment]
Hi, I have already fixed this issue and packaged it as an aur package.

Arch users can install it via `yay -S ch343-dkms` now.

**Comment by cmx0223** [comment]
> Hi, I have already fixed this issue and [packaged it as an aur package](https://aur.archlinux.org/packages/ch343-dkms).
> 
> Arch users can install it via `yay -S ch343-dkms` now.

Thanks for your contribution.
